#
# Makefile for Linux arch/m68k/console source directory
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#

L_TARGET = console.a
obj-y = 68328fb.o fbcon.o fonts.o font_8x16.o font_8x8.o pearl_8x8.o mini_4x6.o

include $(TOPDIR)/Rules.make
