/*
 * WARNING! This file is automatically generated - DO NOT EDIT!
 */

#define TS_MAGICKEY	0x5a5a5a5a
#define TASK_STATE 0
#define TASK_FLAGS 4
#define TASK_PTRACE 24
#define TASK_BLOCKED 742
#define TASK_COUNTER 32
#define TASK_SIGPENDING 8
#define TASK_NEEDRESCHED 20
#define TASK_THREAD 592
#define TASK_MM 44
#define TASK_ACTIVE_MM 80
#define CPUSTAT_SOFTIRQ_ACTIVE 0
#define CPUSTAT_SOFTIRQ_MASK 4
#define THREAD_KSP 0
#define THREAD_USP 4
#define THREAD_SR 8
#define THREAD_FS 10
#define THREAD_CRP 12
#define THREAD_ESP0 20
#define THREAD_FPREG 24
#define THREAD_FPCNTL 120
#define THREAD_FPSTATE 132
#define PT_D0 32
#define PT_ORIG_D0 36
#define PT_D1 0
#define PT_D2 4
#define PT_D3 8
#define PT_D4 12
#define PT_D5 16
#define PT_A0 20
#define PT_A1 24
#define PT_A2 28
#define PT_PC 48
#define PT_SR 46
#define PT_VECTOR 52
#define STAT_IRQ 5148
#define SIGSEGV 11
#define SEGV_MAPERR 196609
#define SIGTRAP 5
#define TRAP_TRACE 196610
#define PT_PTRACED 1
#define PT_TRACESYS 2
#define PT_DTRACE 4
